addons:
  apt:
    packages:
    - python-numpy
    - python-yaml
    - python-scipy
install:
  - pip install flake8  # Not yet available in Ubuntu precise (https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise)
  - pip install -r requirements.txt
language: python
python: "2.7"
script: bash run-travis-tests.sh
sudo: false
virtualenv:
  system_site_packages: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_f6aff9134f80_key -iv $encrypted_f6aff9134f80_iv -in openfisca_bot.enc -out openfisca_bot -d
deploy:
  - provider: script
    skip_cleanup: true
    script: ./release.sh
    on:
      branch: master
